### ISSUE TITLE
clone directory

### ISSUE THREAD

**Issue by GNtem2** [GNtem2/Metaanalysis#2]
@suyiooi 
@ttang19
can you clone my repository Metaanalysis

**Comment by ttang19** [comment]
Done!

**Comment by GNtem2** [comment]
@ttang19 
@suyiooi
you can open the Rmd and xlsx and run in rstudio

**Comment by ttang19** [comment]
The forest plots look okay, but I don't quite understand this:
![Rplot](https://user-images.githubusercontent.com/62630802/77497683-02dcbf00-6ea2-11ea-9269-dfefec6f58f5.png)

**Comment by GNtem2** [comment]
@ttang19 
@suyiooi

 I think this is the data from neurologists. there's more data from the other specialists as well. also remember that this is a platform open to the public.

look at the output in Rstudio

**Comment by suyiooi** [comment]
So is the next step for me to get the raw data from the studies (the 2X 2 table)?

**Comment by GNtem2** [comment]
@suyiooi 
yes. look at the way I structure my data for the spot sign. you should have each study per row and each study attribute in columns. you should have other things like location of assessment (ED, clinic, ward), type of specialist etc
